export const KEYWORDS_SYSML: string[][] = [
  ["APS", "alignment", "phasing system", "subsystems", "TMT", "primary mirror", "segments"],
  ["Observatory model", "TMT project office", "PO", "JPL", "OOSEM", "operational context", "mission", "blackbox specification", "logical", "physical design"],
  ["verification", "timing requirements", "behavioral specification", "as-designed system", "operational", "calibration procedures"],
  ["PEAS", "PIT", "Camera", "M1CS", "ESW", "TCS", "internal components", "external systems"],
  ["state machines", "activities", "APS logical design"],
  ["Post-segment exchange", "Calibrate M1CS Edge Sensors"],
  ["Coarse Tilt Alignment", "Broadband phasing", "Offload Sensor Offsets", "Correcting rigid body", "segment figure", "M3 Alignment", "Narrowband phasing"],
  ["Coarse tilt alignment", "Narrowband phasing", "Broadband phasing 30", "Broadband phasing 100"],
  ["1 um"],
  ["TMT Requirements", "DOORS", "DRD APS", "APS Requirements"],
  ["Verified By", "empty", "not verified"],
  ["APS Interface Requirements", "REQ-2-APS-0010", "multiple Nasmyth locations", "Accepted", "REQ-2-APS-0004", "REQ-2-APS-0052", "Power Distribution"],
  ["no", "L3 APT requirement", "satisfy", "verify", "link"],
  ["Data", "TMT", "Project", "Work Packages", "Telescope", "Control", "Alignment and Phasing System", "Systems Engineering", "Components", "Operational", "APS", "Black Box Specification"],
  ["Components", "Configuration Tables", "Interchange functions", "Interfaces", "Items", "Signals", "PEAS Algorithms"],
  ["M1CS Sensor Calibration with Post Segment-Exchange Alignment", "M2 and M3 Rigid Body Gravity Calibration, Maintenance Alignment", "Off-Axis Measurements", "On-Sky Measurement of Segment Warping Harness Influence Functions", "Post Segment-Exchange Alignment", " Pupil Registration Relative to SH and PIT", "Reference Point Tracking on APT Camera Relative to PIT and SH", "Rigid Body M3 Alignment", "Self Test", "Wavefront Calibration"],
  ["Get installed_Segment_Ack", "Get installed_Segment_Query"],
  ["APS Power Roll-up Standby", "APS Power Roll-up Online", "APS Satisfy Peak Power Analysis"],
  ["APS", "Alignment and Phasing System", "primary mirror", "segments", "alignment"],
  ["primary stakeholders", "APS Development Team", "TMT Observatory Staff"],
  ["Executive Software (ESW)", "the executive software", "provides the framework and support", "command, control and synchronization of components", "observing activities including target and science data acquisition", "GUI", "telescope operator"],
  ["accuracy requirements", "error budgets", "summed", "hierarchically", "roll-up pattern"],
  ["Wavefront Calibration Lookup Table"],
  ["deprecated", "PIT Reference Beam Collection", "SH Reference Beam Collection"],
  ["YY_2016", "YY_2017", "packages"],
  ["no", "duplicated requirements"],
  ["RecycleBin", "no signals", "still referenced", "active diagrams"],
  ["Peak Power Limit Standby Scenario", "Peak Power Limit Online Scenario", "constraints", "Peak Power Limit Requirement JPL", "requirement"],
];