stages:
    - test

test:
    stage: test
    tags:
        - k3s
    image: registry.ai.wu.ac.at/teaming-ai/business-process-management-to-knowledge-graph
    script:
        - python3 ./tests/__init__.py
    only:
        - main
